### ISSUE TITLE
Shallow Clone Post-Mortem

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/blog.cocoapods.org#128]
On March 7, we were made aware of issues users were having cloning the CocoaPods Master Specs Repo (https://github.com/CocoaPods/Specs). The process of determining what was going on happened entirely in https://github.com/CocoaPods/CocoaPods/issues/4989.

- Issues cloning
- GH comment explaining the CPU limiting on their end
- Determined that shallow cloning was the issue
- Suggestions from GH to mitigate
  - Don't shallow clone
  - Don't `git fetch` when it will be a no-op
  - Don't `git fetch` as frequently
  - Don't have a 16,000 item directory
- Shipped 1.0.0.beta.6
  - Fixes all but the last
- Shipped 1.0.0.beta.7
  - Allows us to migrate to a 'sharded' specs directory in the future
- `pod repo shard` (https://github.com/CocoaPods/cocoapods-repo-shard)
  - Will happen some # of months after 1.0.0 final is released
  - Transparent change to users of 1.0+
  - Transparent for anyone using official CocoaPods APIs (web or client)
  - Will break CocoaPods <= 0.39, will need to upgrade or checkout the 0.39 tag
  - Will break anyone who's hardcoded GH links
  - use the new `Source::Metadata` like trunk does and you'll be flexible for the future

Thanks to dantoml, mrackwitz, alloy, orta, vmg, mhagger, mikemcquaid, arthurnn for helping diagnose the issues, formulating & coding up the response, and generally remaining cool in the heat of the moment.

**Comment by segiddins** [comment]
@alloy is there any more information I ought to give for this?

**Comment by alloy** [comment]
@segiddins Nope, I’m planning on writing a draft this weekend.

**Comment by segiddins** [comment]
💕
