### ISSUE TITLE
.xcworkspace does not generate

### ISSUE THREAD

**Issue by ZJNPRI** [CocoaPods/blog.cocoapods.org#143]
Hi,
I'm a beginner for unity.I use cocoaPods to install firebase and admob.
And it generate a default Podfile file.

source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :integrate_targets => false
platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'Firebase/Analytics', '3.14.0'
pod 'Firebase/Core', '3.14.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.13'
end

After pod install,
It can't generate .xcworkspace file.But it apper after I delete "install! 'cocoapods', :integrate_targets => false".
I want to know the meaning of the code, and is it appropriate for me to do so?

Thank you.

**Comment by dnkoutso** [comment]
`:integrate_targets => false` will skip generating a `Pods.xcodeproj` and I believe also an `xcworkspace.

remove that property if you want the workspace to be generated.

**Comment by ZJNPRI** [comment]
Thank you for reply.
The default  generated files like this let beginners troubled.Hope teams can optimize this problem.

**Comment by orta** [comment]
You should raise this with the unity team 👍 

Closing, as this is not particular to us, nor the cocoa pods blog (which is this repo )

**Comment by ZJNPRI** [comment]
At least, you could tell me what "install! 'cocoapods', :integrate_targets => false" means.
https://guides.cocoapods.org/syntax/podfile.html#install_bang
The guides about this is difficult to understand.
