### ISSUE TITLE
Add final call to action for following author

### ISSUE THREAD

**Issue by orta** [CocoaPods/blog.cocoapods.org#47]
![screen shot 2014-09-29 at 13 05 44](https://cloud.githubusercontent.com/assets/49038/4441297/0c88c218-47d1-11e4-91f8-8f0ff8accf5d.png)

As it's unlikely that someone would read the whole post then scroll up, think it makes sense to add this. Open to anyone, probably only a 10-15 minuter

**Comment by segiddins** [comment]
Lol this has been done for forever.
