### ISSUE TITLE
Search 2 blog post notes

### ISSUE THREAD

**Issue by orta** [CocoaPods/blog.cocoapods.org#69]
Initial conversation WWDC 2013 with Alloy + Alexis Gallagher.

People who helped out:

`Florian` - DB/API/Search
`Segiddins` - CocoaDocs / CLOC
`DBGrandi`, `Lazerwalker`, `Phil Tang`, `Danny Hertz` - Fuzzy Alogrithms
`Delisa Mason` - Documentation %
`Clay Allsopp` - README Complexity
`Boris Bungling` - Generating test coverage
`Kyle Fuller` - CocoaDocs maintainance
`Danger` - Rubber ducking

**Comment by floere** [comment]
Is this related to this: http://blog.cocoapods.org/CocoaPods.org-Take-Two/? (And this can be closed?)
Heh, "rubber ducking" reminds me of that time a friend first mistook it for an obscure sexual practice.

**Comment by orta** [comment]
It is, and hah!
