### ISSUE TITLE
Library not found for -lPods-<pod name>; Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by rishigoelbr** [CocoaPods/blog.cocoapods.org#95]
I am setting up xcode bots and my project uses cocoapods. We have a number of private pods and public pods. When the Bot tries to do the Integration it is failing with this error for the first public pod in the list:

Library not found for -lPods-<pod name>
Linker command failed with exit code 1 (use -v to see invocation)

Anyone has an idea of how to get past this?

**Comment by yas375** [comment]
Please ask questions in the Google group instead: https://groups.google.com/forum/#!forum/cocoapods

**Comment by segiddins** [comment]
Yeah, this is the wrong repo.
